Quality assurance page
dynatech/dynaslope3 pull request #164
Opened 2020-10-08 07:51 UTC by HarleOsorio10

2020-10-13 05:08 UTC, ksdelacruz requested changes

2020-10-13 05:08 UTC, ksdelacruz commented on react-ui/web/src/components/monitoring/qa/subcomponents/Table.js
> +                            const limit_start = moment(tableMeta.tableData[tableMeta.rowIndex].ts_limit_start).format("YYYY-MM-DD HH:mm:ss");
refactor na lang ito

2020-10-13 05:39 UTC, HarleOsorio10 commented on react-ui/web/src/components/monitoring/qa/subcomponents/Table.js
> +                            const limit_start = moment(tableMeta.tableData[tableMeta.rowIndex].ts_limit_start).format("YYYY-MM-DD HH:mm:ss");
done

2020-10-19 05:19 UTC, ksdelacruz approved these changes

2020-10-19 05:19 UTC, merged